version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /platforms/windows
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Asia/Shanghai
    groups:
      windows-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
