//
//  MediaClipboardMonitor.swift
//  LiteScreen
//
//  Archives text, media, and file clipboard contents into persistent history.
//

import AppKit
import AVFoundation
import CryptoKit
import Foundation
import UniformTypeIdentifiers

/// Turns capture history into a persistent clipboard.
///
/// Clipboard file URLs are copied into App Support before they are registered so
/// moving or deleting the source does not break the history entry. Bitmap data is
/// normalized to PNG. There is intentionally no item-count, age, or payload-size
/// limit; users retain explicit control through the history clear action.
@MainActor
final class MediaClipboardMonitor {
  static let shared = MediaClipboardMonitor()

  /// Added by LiteScreen's own clipboard writes to avoid re-archiving captures that
  /// are already present in history.
  static let internalWriteMarker = NSPasteboard.PasteboardType("com.ahtcfg24.litescreen.internal-media-write")
  private static let privacyMarkerTypes = Set([
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ])

  private let pasteboard: NSPasteboard
  private let pollInterval: TimeInterval
  private var timer: Timer?
  private var lastChangeCount: Int

  init(
    pasteboard: NSPasteboard = .general,
    pollInterval: TimeInterval = 0.75
  ) {
    self.pasteboard = pasteboard
    self.pollInterval = pollInterval
    lastChangeCount = pasteboard.changeCount
  }

  func start() {
    guard timer == nil else { return }
    lastChangeCount = pasteboard.changeCount
    timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
      Task { @MainActor in
        self?.poll()
      }
    }
    DiagnosticLogger.shared.log(.info, .clipboard, "Media clipboard monitor started")
  }

  func stop() {
    timer?.invalidate()
    timer = nil
    DiagnosticLogger.shared.log(.debug, .clipboard, "Media clipboard monitor stopped")
  }

  private func poll() {
    let changeCount = pasteboard.changeCount
    guard changeCount != lastChangeCount else { return }
    lastChangeCount = changeCount

    guard UserDefaults.standard.object(forKey: PreferencesKeys.mediaClipboardEnabled) as? Bool ?? true else {
      return
    }
    guard pasteboard.types?.contains(Self.internalWriteMarker) != true else { return }
    guard Set(pasteboard.types ?? []).isDisjoint(with: Self.privacyMarkerTypes) else { return }

    if importMediaFileURLs() > 0 {
      return
    }
    if importBitmapImage() {
      return
    }
    importPlainText()
  }

  @discardableResult
  private func importMediaFileURLs() -> Int {
    let options: [NSPasteboard.ReadingOptionKey: Any] = [
      .urlReadingFileURLsOnly: true,
    ]
    guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL] else {
      return 0
    }

    let fileEntries = urls.compactMap { sourceURL -> (URL, CaptureHistoryType)? in
      guard sourceURL.isFileURL else { return nil }
      let type = Self.historyType(for: sourceURL)
      return (sourceURL, type)
    }
    // A Finder/file clipboard is not ordinary text, even when it also exposes a
    // string representation. Consume every file URL here so unknown file types
    // are retained instead of being silently discarded or archived as text.
    guard !fileEntries.isEmpty else { return urls.count }

    Task.detached(priority: .utility) {
      for (sourceURL, historyType) in fileEntries {
        do {
          let sourceAccess = await MainActor.run {
            SandboxFileAccessManager.shared.beginAccessingURL(sourceURL)
          }
          defer { sourceAccess.stop() }

          let archivedURL = try Self.archiveFile(at: sourceURL)
          let duration = await Self.duration(for: archivedURL, type: historyType)
          await MainActor.run {
            guard !CaptureHistoryStore.shared.hasRecord(forFilePath: archivedURL.path) else { return }
            Self.addHistoryRecord(
              for: archivedURL,
              type: historyType,
              duration: duration,
              fileName: sourceURL.lastPathComponent
            )
          }
        } catch {
          DiagnosticLogger.shared.logError(
            .clipboard,
            error,
            "Clipboard file archive failed",
            context: ["fileName": sourceURL.lastPathComponent]
          )
        }
      }
    }
    return fileEntries.count
  }

  @discardableResult
  private func importBitmapImage() -> Bool {
    guard let image = NSImage(pasteboard: pasteboard),
          let tiffData = image.tiffRepresentation
    else {
      return false
    }

    Task.detached(priority: .utility) {
      do {
        guard let representation = NSBitmapImageRep(data: tiffData),
              let pngData = representation.representation(using: .png, properties: [:])
        else { return }
        let digest = SHA256.hash(data: pngData).map { String(format: "%02x", $0) }.joined()
        let destination = try Self.mediaDirectory()
          .appendingPathComponent(digest)
          .appendingPathExtension("png")
        if !FileManager.default.fileExists(atPath: destination.path) {
          try pngData.write(to: destination, options: .atomic)
        }
        let width = representation.pixelsWide
        let height = representation.pixelsHigh
        await MainActor.run {
          guard !CaptureHistoryStore.shared.hasRecord(forFilePath: destination.path) else { return }
          CaptureHistoryStore.shared.addCapture(
            url: destination,
            captureType: .screenshot,
            origin: .clipboard,
            width: width,
            height: height
          )
          DiagnosticLogger.shared.log(
            .info,
            .clipboard,
            "Clipboard image archived to history",
            context: ["fileName": destination.lastPathComponent]
          )
        }
      } catch {
        DiagnosticLogger.shared.logError(.clipboard, error, "Clipboard image archive failed")
      }
    }
    return true
  }

  private func importPlainText() {
    guard let text = pasteboard.string(forType: .string) else { return }
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, let data = text.data(using: .utf8) else { return }

    Task.detached(priority: .utility) {
      do {
        let digest = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        let destination = try Self.mediaDirectory()
          .appendingPathComponent(digest)
          .appendingPathExtension("txt")
        if !FileManager.default.fileExists(atPath: destination.path) {
          try data.write(to: destination, options: .atomic)
        }
        await MainActor.run {
          guard !CaptureHistoryStore.shared.hasRecord(forFilePath: destination.path) else { return }
          CaptureHistoryStore.shared.addCapture(
            url: destination,
            captureType: .text,
            origin: .clipboard
          )
          DiagnosticLogger.shared.log(
            .info,
            .clipboard,
            "Clipboard text archived to history",
            context: ["characterCount": "\(text.count)"]
          )
        }
      } catch {
        DiagnosticLogger.shared.logError(.clipboard, error, "Clipboard text archive failed")
      }
    }
  }

  /// Classifies a pasted file while retaining a generic fallback for every
  /// UTI that is not an image, GIF, or movie.
  nonisolated static func historyType(for url: URL) -> CaptureHistoryType {
    let resourceType = try? url.resourceValues(forKeys: [.contentTypeKey]).contentType
    guard let contentType = resourceType ?? UTType(filenameExtension: url.pathExtension) else { return .file }
    if contentType.conforms(to: .gif) {
      return .gif
    }
    if contentType.conforms(to: .image) {
      return .screenshot
    }
    if contentType.conforms(to: .movie) {
      return .video
    }
    return .file
  }

  private nonisolated static func archiveFile(at sourceURL: URL) throws -> URL {
    let fileManager = FileManager.default
    let digest = try fileDigest(at: sourceURL)
    let ext = sourceURL.pathExtension.isEmpty ? "bin" : sourceURL.pathExtension.lowercased()
    let destination = try mediaDirectory()
      .appendingPathComponent(digest)
      .appendingPathExtension(ext)
    if !fileManager.fileExists(atPath: destination.path) {
      try fileManager.copyItem(at: sourceURL, to: destination)
    }
    return destination
  }

  private nonisolated static func fileDigest(at url: URL) throws -> String {
    let handle = try FileHandle(forReadingFrom: url)
    defer { try? handle.close() }

    var hasher = SHA256()
    while let chunk = try handle.read(upToCount: 1_048_576), !chunk.isEmpty {
      hasher.update(data: chunk)
    }
    return hasher.finalize().map { String(format: "%02x", $0) }.joined()
  }

  private nonisolated static func mediaDirectory() throws -> URL {
    let fileManager = FileManager.default
    let appSupport = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
    let directory = appSupport
      .appendingPathComponent("Lite Screen", isDirectory: true)
      .appendingPathComponent("MediaClipboard", isDirectory: true)
    try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
    return directory
  }

  nonisolated static func isManagedFile(_ url: URL) -> Bool {
    guard let directory = try? mediaDirectory() else { return false }
    return url.standardizedFileURL.path.hasPrefix(directory.standardizedFileURL.path + "/")
  }

  private nonisolated static func duration(
    for url: URL,
    type: CaptureHistoryType
  ) async -> TimeInterval? {
    guard type == .video,
          let value = try? await AVURLAsset(url: url).load(.duration)
    else { return nil }
    let seconds = CMTimeGetSeconds(value)
    return seconds.isFinite && seconds >= 0 ? seconds : nil
  }

  @MainActor private static func addHistoryRecord(
    for url: URL,
    type: CaptureHistoryType,
    duration: TimeInterval?,
    fileName: String
  ) {
    CaptureHistoryStore.shared.addCapture(
      url: url,
      captureType: type,
      origin: .clipboard,
      duration: duration,
      fileName: fileName
    )
    DiagnosticLogger.shared.log(
      .info,
      .clipboard,
      "Clipboard file archived to history",
      context: ["fileName": fileName, "type": type.rawValue]
    )
  }
}
